### DISCUSSION TITLE
todo.txt & yaml-spec?

### DISCUSSION THREAD

**Discussion by ghost** [todotxt/todo.txt#78] [Q&A] [answered]
Hi everyone.

I'm thinking of making a specification of the todo.txt in yaml. I would like to know what you all think of the idea.

#### todo-txt.yaml
```yaml
---
A: 'Search for Best Website ::: https://www.google.com/'
B: 'This is effectively the title ::: this is effectively like a newline or "ignorable" area for most clients'
C: 'Register for appointment at DMV ::: https://some.long.dmv.url.gov/form/some-thing/here.cfm'
D: 'A complicated issue ::: { "json": "blob", "goes": "...here..." }'
```

#### or todo-txt.yaml
```yaml
---
  title: 'search'
  description: 'search for best website'
  completed: 'yes'
```

*what you all think of the idea?*
